# ──────────────────────────────────────────────────────────────
# Stage 1: Base — Install system dependencies
# ──────────────────────────────────────────────────────────────
FROM node:20-alpine AS base
RUN apk add --no-cache libc6-compat

# ──────────────────────────────────────────────────────────────
# Stage 2: Deps — Install production dependencies
# ──────────────────────────────────────────────────────────────
FROM base AS deps
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

# ──────────────────────────────────────────────────────────────
# Stage 3: Builder — Build the Next.js application
# ──────────────────────────────────────────────────────────────
FROM base AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Dummy env vars required for Next.js build (not used at runtime)
ENV MONGODB_URI=process.env.MONGODB_URI
ENV RESEND_API_KEY=process.env.RESEND_API_KEY
ENV SKIP_ENV_VALIDATION=1

# NEXT_PUBLIC_ vars must be baked into the JS bundle at build time
# Pass via: docker build --build-arg NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_...
ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY

RUN npm run build

# ──────────────────────────────────────────────────────────────
# Stage 4: Runner — Production image with minimal artifacts
# ──────────────────────────────────────────────────────────────
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production

# Create non-root user for security
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy standalone output (generated by next.config.ts output: "standalone")
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \
    CMD wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1

CMD ["node", "server.js"]
